// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package proto_message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Response_Status int32

const (
	Response_SUCCESS Response_Status = 0
	Response_FAILURE Response_Status = 1
)

var Response_Status_name = map[int32]string{
	0: "SUCCESS",
	1: "FAILURE",
}
var Response_Status_value = map[string]int32{
	"SUCCESS": 0,
	"FAILURE": 1,
}

func (x Response_Status) String() string {
	return proto.EnumName(Response_Status_name, int32(x))
}
func (Response_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_message_f30f0df9d4e5e4d8, []int{0, 0}
}

type Response struct {
	Status               Response_Status `protobuf:"varint,1,opt,name=status,proto3,enum=proto.message.Response_Status" json:"status,omitempty"`
	Message              string          `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_f30f0df9d4e5e4d8, []int{0}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() Response_Status {
	if m != nil {
		return m.Status
	}
	return Response_SUCCESS
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// a protocol define a set of reuqest and responses
type AddPeerRequest struct {
	// method specific data
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPeerRequest) Reset()         { *m = AddPeerRequest{} }
func (m *AddPeerRequest) String() string { return proto.CompactTextString(m) }
func (*AddPeerRequest) ProtoMessage()    {}
func (*AddPeerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_f30f0df9d4e5e4d8, []int{1}
}
func (m *AddPeerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPeerRequest.Unmarshal(m, b)
}
func (m *AddPeerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPeerRequest.Marshal(b, m, deterministic)
}
func (dst *AddPeerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPeerRequest.Merge(dst, src)
}
func (m *AddPeerRequest) XXX_Size() int {
	return xxx_messageInfo_AddPeerRequest.Size(m)
}
func (m *AddPeerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPeerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddPeerRequest proto.InternalMessageInfo

func (m *AddPeerRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AddPeerResponse struct {
	// response specific data
	Response             *Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddPeerResponse) Reset()         { *m = AddPeerResponse{} }
func (m *AddPeerResponse) String() string { return proto.CompactTextString(m) }
func (*AddPeerResponse) ProtoMessage()    {}
func (*AddPeerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_f30f0df9d4e5e4d8, []int{2}
}
func (m *AddPeerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPeerResponse.Unmarshal(m, b)
}
func (m *AddPeerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPeerResponse.Marshal(b, m, deterministic)
}
func (dst *AddPeerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPeerResponse.Merge(dst, src)
}
func (m *AddPeerResponse) XXX_Size() int {
	return xxx_messageInfo_AddPeerResponse.Size(m)
}
func (m *AddPeerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPeerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddPeerResponse proto.InternalMessageInfo

func (m *AddPeerResponse) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

type Collation struct {
	ShardID              int64    `protobuf:"varint,1,opt,name=shardID,proto3" json:"shardID,omitempty"`
	Period               int64    `protobuf:"varint,2,opt,name=period,proto3" json:"period,omitempty"`
	Blobs                string   `protobuf:"bytes,3,opt,name=blobs,proto3" json:"blobs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Collation) Reset()         { *m = Collation{} }
func (m *Collation) String() string { return proto.CompactTextString(m) }
func (*Collation) ProtoMessage()    {}
func (*Collation) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_f30f0df9d4e5e4d8, []int{3}
}
func (m *Collation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Collation.Unmarshal(m, b)
}
func (m *Collation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Collation.Marshal(b, m, deterministic)
}
func (dst *Collation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Collation.Merge(dst, src)
}
func (m *Collation) XXX_Size() int {
	return xxx_messageInfo_Collation.Size(m)
}
func (m *Collation) XXX_DiscardUnknown() {
	xxx_messageInfo_Collation.DiscardUnknown(m)
}

var xxx_messageInfo_Collation proto.InternalMessageInfo

func (m *Collation) GetShardID() int64 {
	if m != nil {
		return m.ShardID
	}
	return 0
}

func (m *Collation) GetPeriod() int64 {
	if m != nil {
		return m.Period
	}
	return 0
}

func (m *Collation) GetBlobs() string {
	if m != nil {
		return m.Blobs
	}
	return ""
}

type CollationRequest struct {
	ShardID              int64    `protobuf:"varint,1,opt,name=shardID,proto3" json:"shardID,omitempty"`
	Period               int64    `protobuf:"varint,2,opt,name=period,proto3" json:"period,omitempty"`
	Hash                 string   `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollationRequest) Reset()         { *m = CollationRequest{} }
func (m *CollationRequest) String() string { return proto.CompactTextString(m) }
func (*CollationRequest) ProtoMessage()    {}
func (*CollationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_f30f0df9d4e5e4d8, []int{4}
}
func (m *CollationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollationRequest.Unmarshal(m, b)
}
func (m *CollationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollationRequest.Marshal(b, m, deterministic)
}
func (dst *CollationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollationRequest.Merge(dst, src)
}
func (m *CollationRequest) XXX_Size() int {
	return xxx_messageInfo_CollationRequest.Size(m)
}
func (m *CollationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CollationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CollationRequest proto.InternalMessageInfo

func (m *CollationRequest) GetShardID() int64 {
	if m != nil {
		return m.ShardID
	}
	return 0
}

func (m *CollationRequest) GetPeriod() int64 {
	if m != nil {
		return m.Period
	}
	return 0
}

func (m *CollationRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type CollationResponse struct {
	Response             *Response  `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Collation            *Collation `protobuf:"bytes,2,opt,name=collation,proto3" json:"collation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CollationResponse) Reset()         { *m = CollationResponse{} }
func (m *CollationResponse) String() string { return proto.CompactTextString(m) }
func (*CollationResponse) ProtoMessage()    {}
func (*CollationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_f30f0df9d4e5e4d8, []int{5}
}
func (m *CollationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollationResponse.Unmarshal(m, b)
}
func (m *CollationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollationResponse.Marshal(b, m, deterministic)
}
func (dst *CollationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollationResponse.Merge(dst, src)
}
func (m *CollationResponse) XXX_Size() int {
	return xxx_messageInfo_CollationResponse.Size(m)
}
func (m *CollationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CollationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CollationResponse proto.InternalMessageInfo

func (m *CollationResponse) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *CollationResponse) GetCollation() *Collation {
	if m != nil {
		return m.Collation
	}
	return nil
}

type ShardPeerRequest struct {
	ShardIDs             []int64  `protobuf:"varint,1,rep,packed,name=shardIDs,proto3" json:"shardIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShardPeerRequest) Reset()         { *m = ShardPeerRequest{} }
func (m *ShardPeerRequest) String() string { return proto.CompactTextString(m) }
func (*ShardPeerRequest) ProtoMessage()    {}
func (*ShardPeerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_f30f0df9d4e5e4d8, []int{6}
}
func (m *ShardPeerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShardPeerRequest.Unmarshal(m, b)
}
func (m *ShardPeerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShardPeerRequest.Marshal(b, m, deterministic)
}
func (dst *ShardPeerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardPeerRequest.Merge(dst, src)
}
func (m *ShardPeerRequest) XXX_Size() int {
	return xxx_messageInfo_ShardPeerRequest.Size(m)
}
func (m *ShardPeerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardPeerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShardPeerRequest proto.InternalMessageInfo

func (m *ShardPeerRequest) GetShardIDs() []int64 {
	if m != nil {
		return m.ShardIDs
	}
	return nil
}

type ShardPeerResponse struct {
	Response             *Response                          `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	ShardPeers           map[int64]*ShardPeerResponse_Peers `protobuf:"bytes,2,rep,name=shardPeers,proto3" json:"shardPeers,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *ShardPeerResponse) Reset()         { *m = ShardPeerResponse{} }
func (m *ShardPeerResponse) String() string { return proto.CompactTextString(m) }
func (*ShardPeerResponse) ProtoMessage()    {}
func (*ShardPeerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_f30f0df9d4e5e4d8, []int{7}
}
func (m *ShardPeerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShardPeerResponse.Unmarshal(m, b)
}
func (m *ShardPeerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShardPeerResponse.Marshal(b, m, deterministic)
}
func (dst *ShardPeerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardPeerResponse.Merge(dst, src)
}
func (m *ShardPeerResponse) XXX_Size() int {
	return xxx_messageInfo_ShardPeerResponse.Size(m)
}
func (m *ShardPeerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardPeerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShardPeerResponse proto.InternalMessageInfo

func (m *ShardPeerResponse) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *ShardPeerResponse) GetShardPeers() map[int64]*ShardPeerResponse_Peers {
	if m != nil {
		return m.ShardPeers
	}
	return nil
}

type ShardPeerResponse_Peers struct {
	Peers                []string `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShardPeerResponse_Peers) Reset()         { *m = ShardPeerResponse_Peers{} }
func (m *ShardPeerResponse_Peers) String() string { return proto.CompactTextString(m) }
func (*ShardPeerResponse_Peers) ProtoMessage()    {}
func (*ShardPeerResponse_Peers) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_f30f0df9d4e5e4d8, []int{7, 0}
}
func (m *ShardPeerResponse_Peers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShardPeerResponse_Peers.Unmarshal(m, b)
}
func (m *ShardPeerResponse_Peers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShardPeerResponse_Peers.Marshal(b, m, deterministic)
}
func (dst *ShardPeerResponse_Peers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardPeerResponse_Peers.Merge(dst, src)
}
func (m *ShardPeerResponse_Peers) XXX_Size() int {
	return xxx_messageInfo_ShardPeerResponse_Peers.Size(m)
}
func (m *ShardPeerResponse_Peers) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardPeerResponse_Peers.DiscardUnknown(m)
}

var xxx_messageInfo_ShardPeerResponse_Peers proto.InternalMessageInfo

func (m *ShardPeerResponse_Peers) GetPeers() []string {
	if m != nil {
		return m.Peers
	}
	return nil
}

type NotifyShardsRequest struct {
	ShardIDs             []int64  `protobuf:"varint,1,rep,packed,name=shardIDs,proto3" json:"shardIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyShardsRequest) Reset()         { *m = NotifyShardsRequest{} }
func (m *NotifyShardsRequest) String() string { return proto.CompactTextString(m) }
func (*NotifyShardsRequest) ProtoMessage()    {}
func (*NotifyShardsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_f30f0df9d4e5e4d8, []int{8}
}
func (m *NotifyShardsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyShardsRequest.Unmarshal(m, b)
}
func (m *NotifyShardsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyShardsRequest.Marshal(b, m, deterministic)
}
func (dst *NotifyShardsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyShardsRequest.Merge(dst, src)
}
func (m *NotifyShardsRequest) XXX_Size() int {
	return xxx_messageInfo_NotifyShardsRequest.Size(m)
}
func (m *NotifyShardsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyShardsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyShardsRequest proto.InternalMessageInfo

func (m *NotifyShardsRequest) GetShardIDs() []int64 {
	if m != nil {
		return m.ShardIDs
	}
	return nil
}

func init() {
	proto.RegisterType((*Response)(nil), "proto.message.Response")
	proto.RegisterType((*AddPeerRequest)(nil), "proto.message.AddPeerRequest")
	proto.RegisterType((*AddPeerResponse)(nil), "proto.message.AddPeerResponse")
	proto.RegisterType((*Collation)(nil), "proto.message.Collation")
	proto.RegisterType((*CollationRequest)(nil), "proto.message.CollationRequest")
	proto.RegisterType((*CollationResponse)(nil), "proto.message.CollationResponse")
	proto.RegisterType((*ShardPeerRequest)(nil), "proto.message.ShardPeerRequest")
	proto.RegisterType((*ShardPeerResponse)(nil), "proto.message.ShardPeerResponse")
	proto.RegisterMapType((map[int64]*ShardPeerResponse_Peers)(nil), "proto.message.ShardPeerResponse.ShardPeersEntry")
	proto.RegisterType((*ShardPeerResponse_Peers)(nil), "proto.message.ShardPeerResponse.Peers")
	proto.RegisterType((*NotifyShardsRequest)(nil), "proto.message.NotifyShardsRequest")
	proto.RegisterEnum("proto.message.Response_Status", Response_Status_name, Response_Status_value)
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_message_f30f0df9d4e5e4d8) }

var fileDescriptor_message_f30f0df9d4e5e4d8 = []byte{
	// 412 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xc1, 0x8b, 0xda, 0x40,
	0x14, 0xc6, 0x9b, 0xa4, 0x46, 0xf3, 0x82, 0x1a, 0xa7, 0xa5, 0x0d, 0x42, 0x8b, 0xcc, 0xa1, 0x84,
	0x1e, 0x42, 0x1b, 0x41, 0x4a, 0xe9, 0x45, 0xac, 0x82, 0x50, 0x8a, 0x4c, 0x10, 0x7a, 0x8d, 0xcd,
	0xec, 0x2a, 0x9b, 0x75, 0xb2, 0x99, 0xb8, 0xe0, 0x6d, 0xff, 0x94, 0xfd, 0x53, 0x97, 0x99, 0x4c,
	0x62, 0x74, 0x59, 0x76, 0x17, 0x4f, 0xbe, 0x2f, 0x7c, 0xef, 0xf7, 0xbe, 0x37, 0x4f, 0x68, 0x5f,
	0x53, 0xce, 0xa3, 0x4b, 0xea, 0xa7, 0x19, 0xcb, 0x19, 0x6a, 0xcb, 0x1f, 0x5f, 0x7d, 0xc4, 0x77,
	0x1a, 0xb4, 0x08, 0xe5, 0x29, 0xdb, 0x72, 0x8a, 0x46, 0x60, 0xf2, 0x3c, 0xca, 0x77, 0xdc, 0xd5,
	0x06, 0x9a, 0xd7, 0x09, 0x3e, 0xfb, 0x47, 0x66, 0xbf, 0x34, 0xfa, 0xa1, 0x74, 0x11, 0xe5, 0x46,
	0x2e, 0x34, 0x95, 0xc5, 0xd5, 0x07, 0x9a, 0x67, 0x91, 0x52, 0x62, 0x0c, 0x66, 0xe1, 0x45, 0x36,
	0x34, 0xc3, 0xe5, 0x64, 0x32, 0x0d, 0x43, 0xe7, 0x8d, 0x10, 0xb3, 0xf1, 0xfc, 0xcf, 0x92, 0x4c,
	0x1d, 0x0d, 0x7f, 0x85, 0xce, 0x38, 0x8e, 0x17, 0x94, 0x66, 0x84, 0xde, 0xec, 0x28, 0xcf, 0xeb,
	0x3c, 0xed, 0x98, 0x37, 0x83, 0x6e, 0xe5, 0x55, 0xa1, 0x87, 0xd0, 0xca, 0x54, 0x2d, 0xdd, 0x76,
	0xf0, 0xf1, 0x89, 0xd8, 0xa4, 0x32, 0xe2, 0x10, 0xac, 0x09, 0x4b, 0x92, 0x28, 0xdf, 0xb0, 0xad,
	0x18, 0xc7, 0xd7, 0x51, 0x16, 0xcf, 0x7f, 0x4b, 0x80, 0x41, 0x4a, 0x89, 0x3e, 0x80, 0x99, 0xd2,
	0x6c, 0xc3, 0x62, 0xb9, 0x97, 0x41, 0x94, 0x42, 0xef, 0xa1, 0xb1, 0x4a, 0xd8, 0x8a, 0xbb, 0x86,
	0x8c, 0x57, 0x08, 0xfc, 0x0f, 0x9c, 0x0a, 0x5a, 0x5b, 0xe5, 0x95, 0x6c, 0x04, 0x6f, 0xd7, 0x11,
	0x5f, 0x2b, 0xb4, 0xac, 0xc5, 0x95, 0x7a, 0x35, 0xf4, 0x19, 0x9b, 0xa3, 0x11, 0x58, 0xff, 0x4b,
	0x92, 0x9c, 0x6c, 0x07, 0xee, 0x49, 0xd7, 0x61, 0xd2, 0xc1, 0x8a, 0x7d, 0x70, 0x42, 0x91, 0xbc,
	0x7e, 0xa7, 0x3e, 0xb4, 0xd4, 0x36, 0xe2, 0x1f, 0x63, 0x78, 0x06, 0xa9, 0x34, 0xbe, 0xd7, 0xa1,
	0x57, 0x6b, 0x38, 0x27, 0xf2, 0x02, 0x80, 0x97, 0x24, 0xee, 0xea, 0x03, 0xc3, 0xb3, 0x83, 0x6f,
	0x27, 0x6d, 0x8f, 0x46, 0x1d, 0xbe, 0xf0, 0xe9, 0x36, 0xcf, 0xf6, 0xa4, 0xc6, 0xe8, 0x7f, 0x82,
	0x86, 0x2c, 0xc4, 0x21, 0x53, 0x49, 0x15, 0xf1, 0x2d, 0x52, 0x88, 0x3e, 0x85, 0xee, 0x49, 0x37,
	0x72, 0xc0, 0xb8, 0xa2, 0x7b, 0x75, 0x43, 0x51, 0xa2, 0x5f, 0xd0, 0xb8, 0x8d, 0x92, 0x1d, 0x55,
	0x8f, 0xf8, 0xe5, 0xd9, 0x40, 0x92, 0x46, 0x8a, 0xa6, 0x9f, 0xfa, 0x0f, 0x0d, 0x7f, 0x87, 0x77,
	0x7f, 0x59, 0xbe, 0xb9, 0xd8, 0x4b, 0x2f, 0x7f, 0xc1, 0xab, 0xae, 0x4c, 0x39, 0x64, 0xf8, 0x10,
	0x00, 0x00, 0xff, 0xff, 0x45, 0xaa, 0xc6, 0x88, 0xd5, 0x03, 0x00, 0x00,
}
