// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package proto_message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Response_Status int32

const (
	Response_SUCCESS Response_Status = 0
	Response_FAILURE Response_Status = 1
)

var Response_Status_name = map[int32]string{
	0: "SUCCESS",
	1: "FAILURE",
}
var Response_Status_value = map[string]int32{
	"SUCCESS": 0,
	"FAILURE": 1,
}

func (x Response_Status) String() string {
	return proto.EnumName(Response_Status_name, int32(x))
}
func (Response_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_message_c34169316457c97f, []int{0, 0}
}

type Response struct {
	Status               Response_Status `protobuf:"varint,1,opt,name=status,proto3,enum=proto.message.Response_Status" json:"status,omitempty"`
	Message              string          `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_c34169316457c97f, []int{0}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() Response_Status {
	if m != nil {
		return m.Status
	}
	return Response_SUCCESS
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AddPeerRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPeerRequest) Reset()         { *m = AddPeerRequest{} }
func (m *AddPeerRequest) String() string { return proto.CompactTextString(m) }
func (*AddPeerRequest) ProtoMessage()    {}
func (*AddPeerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_c34169316457c97f, []int{1}
}
func (m *AddPeerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPeerRequest.Unmarshal(m, b)
}
func (m *AddPeerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPeerRequest.Marshal(b, m, deterministic)
}
func (dst *AddPeerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPeerRequest.Merge(dst, src)
}
func (m *AddPeerRequest) XXX_Size() int {
	return xxx_messageInfo_AddPeerRequest.Size(m)
}
func (m *AddPeerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPeerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddPeerRequest proto.InternalMessageInfo

func (m *AddPeerRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AddPeerResponse struct {
	Response             *Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddPeerResponse) Reset()         { *m = AddPeerResponse{} }
func (m *AddPeerResponse) String() string { return proto.CompactTextString(m) }
func (*AddPeerResponse) ProtoMessage()    {}
func (*AddPeerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_c34169316457c97f, []int{2}
}
func (m *AddPeerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPeerResponse.Unmarshal(m, b)
}
func (m *AddPeerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPeerResponse.Marshal(b, m, deterministic)
}
func (dst *AddPeerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPeerResponse.Merge(dst, src)
}
func (m *AddPeerResponse) XXX_Size() int {
	return xxx_messageInfo_AddPeerResponse.Size(m)
}
func (m *AddPeerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPeerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddPeerResponse proto.InternalMessageInfo

func (m *AddPeerResponse) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

type Collation struct {
	ShardID              int64    `protobuf:"varint,1,opt,name=shardID,proto3" json:"shardID,omitempty"`
	Period               int64    `protobuf:"varint,2,opt,name=period,proto3" json:"period,omitempty"`
	Blobs                []byte   `protobuf:"bytes,3,opt,name=blobs,proto3" json:"blobs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Collation) Reset()         { *m = Collation{} }
func (m *Collation) String() string { return proto.CompactTextString(m) }
func (*Collation) ProtoMessage()    {}
func (*Collation) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_c34169316457c97f, []int{3}
}
func (m *Collation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Collation.Unmarshal(m, b)
}
func (m *Collation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Collation.Marshal(b, m, deterministic)
}
func (dst *Collation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Collation.Merge(dst, src)
}
func (m *Collation) XXX_Size() int {
	return xxx_messageInfo_Collation.Size(m)
}
func (m *Collation) XXX_DiscardUnknown() {
	xxx_messageInfo_Collation.DiscardUnknown(m)
}

var xxx_messageInfo_Collation proto.InternalMessageInfo

func (m *Collation) GetShardID() int64 {
	if m != nil {
		return m.ShardID
	}
	return 0
}

func (m *Collation) GetPeriod() int64 {
	if m != nil {
		return m.Period
	}
	return 0
}

func (m *Collation) GetBlobs() []byte {
	if m != nil {
		return m.Blobs
	}
	return nil
}

type CollationRequest struct {
	ShardID              int64    `protobuf:"varint,1,opt,name=shardID,proto3" json:"shardID,omitempty"`
	Period               int64    `protobuf:"varint,2,opt,name=period,proto3" json:"period,omitempty"`
	Hash                 string   `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollationRequest) Reset()         { *m = CollationRequest{} }
func (m *CollationRequest) String() string { return proto.CompactTextString(m) }
func (*CollationRequest) ProtoMessage()    {}
func (*CollationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_c34169316457c97f, []int{4}
}
func (m *CollationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollationRequest.Unmarshal(m, b)
}
func (m *CollationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollationRequest.Marshal(b, m, deterministic)
}
func (dst *CollationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollationRequest.Merge(dst, src)
}
func (m *CollationRequest) XXX_Size() int {
	return xxx_messageInfo_CollationRequest.Size(m)
}
func (m *CollationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CollationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CollationRequest proto.InternalMessageInfo

func (m *CollationRequest) GetShardID() int64 {
	if m != nil {
		return m.ShardID
	}
	return 0
}

func (m *CollationRequest) GetPeriod() int64 {
	if m != nil {
		return m.Period
	}
	return 0
}

func (m *CollationRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type CollationResponse struct {
	Response             *Response  `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Collation            *Collation `protobuf:"bytes,2,opt,name=collation,proto3" json:"collation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CollationResponse) Reset()         { *m = CollationResponse{} }
func (m *CollationResponse) String() string { return proto.CompactTextString(m) }
func (*CollationResponse) ProtoMessage()    {}
func (*CollationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_c34169316457c97f, []int{5}
}
func (m *CollationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollationResponse.Unmarshal(m, b)
}
func (m *CollationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollationResponse.Marshal(b, m, deterministic)
}
func (dst *CollationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollationResponse.Merge(dst, src)
}
func (m *CollationResponse) XXX_Size() int {
	return xxx_messageInfo_CollationResponse.Size(m)
}
func (m *CollationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CollationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CollationResponse proto.InternalMessageInfo

func (m *CollationResponse) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *CollationResponse) GetCollation() *Collation {
	if m != nil {
		return m.Collation
	}
	return nil
}

type ShardPeerRequest struct {
	ShardIDs             []int64  `protobuf:"varint,1,rep,packed,name=shardIDs,proto3" json:"shardIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShardPeerRequest) Reset()         { *m = ShardPeerRequest{} }
func (m *ShardPeerRequest) String() string { return proto.CompactTextString(m) }
func (*ShardPeerRequest) ProtoMessage()    {}
func (*ShardPeerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_c34169316457c97f, []int{6}
}
func (m *ShardPeerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShardPeerRequest.Unmarshal(m, b)
}
func (m *ShardPeerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShardPeerRequest.Marshal(b, m, deterministic)
}
func (dst *ShardPeerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardPeerRequest.Merge(dst, src)
}
func (m *ShardPeerRequest) XXX_Size() int {
	return xxx_messageInfo_ShardPeerRequest.Size(m)
}
func (m *ShardPeerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardPeerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShardPeerRequest proto.InternalMessageInfo

func (m *ShardPeerRequest) GetShardIDs() []int64 {
	if m != nil {
		return m.ShardIDs
	}
	return nil
}

type Peers struct {
	Peers                []string `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Peers) Reset()         { *m = Peers{} }
func (m *Peers) String() string { return proto.CompactTextString(m) }
func (*Peers) ProtoMessage()    {}
func (*Peers) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_c34169316457c97f, []int{7}
}
func (m *Peers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Peers.Unmarshal(m, b)
}
func (m *Peers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Peers.Marshal(b, m, deterministic)
}
func (dst *Peers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Peers.Merge(dst, src)
}
func (m *Peers) XXX_Size() int {
	return xxx_messageInfo_Peers.Size(m)
}
func (m *Peers) XXX_DiscardUnknown() {
	xxx_messageInfo_Peers.DiscardUnknown(m)
}

var xxx_messageInfo_Peers proto.InternalMessageInfo

func (m *Peers) GetPeers() []string {
	if m != nil {
		return m.Peers
	}
	return nil
}

type ShardPeerResponse struct {
	Response             *Response        `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	ShardPeers           map[int64]*Peers `protobuf:"bytes,2,rep,name=shardPeers,proto3" json:"shardPeers,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ShardPeerResponse) Reset()         { *m = ShardPeerResponse{} }
func (m *ShardPeerResponse) String() string { return proto.CompactTextString(m) }
func (*ShardPeerResponse) ProtoMessage()    {}
func (*ShardPeerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_c34169316457c97f, []int{8}
}
func (m *ShardPeerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShardPeerResponse.Unmarshal(m, b)
}
func (m *ShardPeerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShardPeerResponse.Marshal(b, m, deterministic)
}
func (dst *ShardPeerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardPeerResponse.Merge(dst, src)
}
func (m *ShardPeerResponse) XXX_Size() int {
	return xxx_messageInfo_ShardPeerResponse.Size(m)
}
func (m *ShardPeerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardPeerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShardPeerResponse proto.InternalMessageInfo

func (m *ShardPeerResponse) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *ShardPeerResponse) GetShardPeers() map[int64]*Peers {
	if m != nil {
		return m.ShardPeers
	}
	return nil
}

func init() {
	proto.RegisterType((*Response)(nil), "proto.message.Response")
	proto.RegisterType((*AddPeerRequest)(nil), "proto.message.AddPeerRequest")
	proto.RegisterType((*AddPeerResponse)(nil), "proto.message.AddPeerResponse")
	proto.RegisterType((*Collation)(nil), "proto.message.Collation")
	proto.RegisterType((*CollationRequest)(nil), "proto.message.CollationRequest")
	proto.RegisterType((*CollationResponse)(nil), "proto.message.CollationResponse")
	proto.RegisterType((*ShardPeerRequest)(nil), "proto.message.ShardPeerRequest")
	proto.RegisterType((*Peers)(nil), "proto.message.Peers")
	proto.RegisterType((*ShardPeerResponse)(nil), "proto.message.ShardPeerResponse")
	proto.RegisterMapType((map[int64]*Peers)(nil), "proto.message.ShardPeerResponse.ShardPeersEntry")
	proto.RegisterEnum("proto.message.Response_Status", Response_Status_name, Response_Status_value)
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_message_c34169316457c97f) }

var fileDescriptor_message_c34169316457c97f = []byte{
	// 399 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0x41, 0x8b, 0xda, 0x40,
	0x14, 0xc7, 0x3b, 0xa6, 0x46, 0xf3, 0x52, 0x35, 0x0e, 0xd2, 0x06, 0xa1, 0x25, 0xcc, 0x29, 0x78,
	0x08, 0x25, 0x82, 0x94, 0xde, 0xc4, 0x2a, 0x08, 0x3d, 0xc8, 0x04, 0xa1, 0xd7, 0xd8, 0x0c, 0xab,
	0x6c, 0xd6, 0x64, 0x33, 0x71, 0xc1, 0xdb, 0x7e, 0xe3, 0xfd, 0x0a, 0xcb, 0x4c, 0x26, 0x31, 0x66,
	0xd9, 0xc3, 0xe2, 0x29, 0xef, 0x3f, 0xf3, 0x7b, 0xff, 0xf7, 0xde, 0xbc, 0x40, 0xef, 0x81, 0x71,
	0x1e, 0xde, 0x31, 0x2f, 0xcd, 0x92, 0x3c, 0xc1, 0x3d, 0xf9, 0xf1, 0xd4, 0x21, 0x79, 0x46, 0xd0,
	0xa5, 0x8c, 0xa7, 0xc9, 0x91, 0x33, 0x3c, 0x03, 0x9d, 0xe7, 0x61, 0x7e, 0xe2, 0x36, 0x72, 0x90,
	0xdb, 0xf7, 0x7f, 0x78, 0x57, 0xb0, 0x57, 0x82, 0x5e, 0x20, 0x29, 0xaa, 0x68, 0x6c, 0x43, 0x47,
	0x21, 0x76, 0xcb, 0x41, 0xae, 0x41, 0x4b, 0x49, 0x08, 0xe8, 0x05, 0x8b, 0x4d, 0xe8, 0x04, 0xdb,
	0xc5, 0x62, 0x19, 0x04, 0xd6, 0x27, 0x21, 0x56, 0xf3, 0xf5, 0xdf, 0x2d, 0x5d, 0x5a, 0x88, 0x4c,
	0xa0, 0x3f, 0x8f, 0xa2, 0x0d, 0x63, 0x19, 0x65, 0x8f, 0x27, 0xc6, 0xf3, 0xba, 0x1f, 0xba, 0xf6,
	0x5b, 0xc1, 0xa0, 0x62, 0x55, 0xd3, 0x53, 0xe8, 0x66, 0x2a, 0x96, 0xb4, 0xe9, 0x7f, 0x7b, 0xa7,
	0x6d, 0x5a, 0x81, 0x24, 0x00, 0x63, 0x91, 0xc4, 0x71, 0x98, 0x1f, 0x92, 0xa3, 0x28, 0xc7, 0xf7,
	0x61, 0x16, 0xad, 0xff, 0x48, 0x03, 0x8d, 0x96, 0x12, 0x7f, 0x05, 0x3d, 0x65, 0xd9, 0x21, 0x89,
	0xe4, 0x5c, 0x1a, 0x55, 0x0a, 0x8f, 0xa0, 0xbd, 0x8b, 0x93, 0x1d, 0xb7, 0x35, 0x07, 0xb9, 0x5f,
	0x68, 0x21, 0xc8, 0x3f, 0xb0, 0x2a, 0xd3, 0xda, 0x28, 0x1f, 0xf4, 0xc6, 0xf0, 0x79, 0x1f, 0xf2,
	0xbd, 0xb4, 0x36, 0xa8, 0x8c, 0xc5, 0x96, 0x86, 0x35, 0xeb, 0x1b, 0x26, 0xc7, 0x33, 0x30, 0xfe,
	0x97, 0x4e, 0xb2, 0xb2, 0xe9, 0xdb, 0x8d, 0xac, 0x4b, 0xa5, 0x0b, 0x4a, 0x3c, 0xb0, 0x02, 0xd1,
	0x79, 0x7d, 0x4f, 0x63, 0xe8, 0xaa, 0x69, 0xc4, 0x1f, 0xa3, 0xb9, 0x1a, 0xad, 0x34, 0xf9, 0x0e,
	0x6d, 0x81, 0x72, 0xf1, 0x56, 0xa9, 0x08, 0x24, 0x61, 0xd0, 0x42, 0x90, 0x17, 0x04, 0xc3, 0x9a,
	0xdf, 0x2d, 0x13, 0x6d, 0x00, 0x78, 0xe9, 0xc4, 0xed, 0x96, 0xa3, 0xb9, 0xa6, 0xff, 0xb3, 0x91,
	0xf6, 0xa6, 0xd4, 0xe5, 0x84, 0x2f, 0x8f, 0x79, 0x76, 0xa6, 0x35, 0x8f, 0x71, 0x00, 0x83, 0xc6,
	0x35, 0xb6, 0x40, 0xbb, 0x67, 0x67, 0xb5, 0x43, 0x11, 0xe2, 0x09, 0xb4, 0x9f, 0xc2, 0xf8, 0xc4,
	0xd4, 0x23, 0x8e, 0x1a, 0x15, 0x65, 0x2e, 0x2d, 0x90, 0xdf, 0xad, 0x5f, 0x68, 0xa7, 0xcb, 0xfb,
	0xe9, 0x6b, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc2, 0xd7, 0x8a, 0x0e, 0x90, 0x03, 0x00, 0x00,
}
