// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package proto_event

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import message "github.com/ethresearch/sharding-p2p-poc/pb/message"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Response_Status int32

const (
	Response_SUCCESS Response_Status = 0
	Response_FAILURE Response_Status = 1
)

var Response_Status_name = map[int32]string{
	0: "SUCCESS",
	1: "FAILURE",
}

var Response_Status_value = map[string]int32{
	"SUCCESS": 0,
	"FAILURE": 1,
}

func (x Response_Status) String() string {
	return proto.EnumName(Response_Status_name, int32(x))
}

func (Response_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{7, 0}
}

type MetaMsg struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetaMsg) Reset()         { *m = MetaMsg{} }
func (m *MetaMsg) String() string { return proto.CompactTextString(m) }
func (*MetaMsg) ProtoMessage()    {}
func (*MetaMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0}
}
func (m *MetaMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaMsg.Unmarshal(m, b)
}
func (m *MetaMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaMsg.Marshal(b, m, deterministic)
}
func (m *MetaMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaMsg.Merge(m, src)
}
func (m *MetaMsg) XXX_Size() int {
	return xxx_messageInfo_MetaMsg.Size(m)
}
func (m *MetaMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaMsg.DiscardUnknown(m)
}

var xxx_messageInfo_MetaMsg proto.InternalMessageInfo

type NotifyCollationRequest struct {
	MetaMsg              *MetaMsg           `protobuf:"bytes,1,opt,name=metaMsg,proto3" json:"metaMsg,omitempty"`
	Collation            *message.Collation `protobuf:"bytes,2,opt,name=collation,proto3" json:"collation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *NotifyCollationRequest) Reset()         { *m = NotifyCollationRequest{} }
func (m *NotifyCollationRequest) String() string { return proto.CompactTextString(m) }
func (*NotifyCollationRequest) ProtoMessage()    {}
func (*NotifyCollationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{1}
}
func (m *NotifyCollationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyCollationRequest.Unmarshal(m, b)
}
func (m *NotifyCollationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyCollationRequest.Marshal(b, m, deterministic)
}
func (m *NotifyCollationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyCollationRequest.Merge(m, src)
}
func (m *NotifyCollationRequest) XXX_Size() int {
	return xxx_messageInfo_NotifyCollationRequest.Size(m)
}
func (m *NotifyCollationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyCollationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyCollationRequest proto.InternalMessageInfo

func (m *NotifyCollationRequest) GetMetaMsg() *MetaMsg {
	if m != nil {
		return m.MetaMsg
	}
	return nil
}

func (m *NotifyCollationRequest) GetCollation() *message.Collation {
	if m != nil {
		return m.Collation
	}
	return nil
}

type NotifyCollationResponse struct {
	Response             *Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	IsValid              bool      `protobuf:"varint,2,opt,name=isValid,proto3" json:"isValid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *NotifyCollationResponse) Reset()         { *m = NotifyCollationResponse{} }
func (m *NotifyCollationResponse) String() string { return proto.CompactTextString(m) }
func (*NotifyCollationResponse) ProtoMessage()    {}
func (*NotifyCollationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{2}
}
func (m *NotifyCollationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyCollationResponse.Unmarshal(m, b)
}
func (m *NotifyCollationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyCollationResponse.Marshal(b, m, deterministic)
}
func (m *NotifyCollationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyCollationResponse.Merge(m, src)
}
func (m *NotifyCollationResponse) XXX_Size() int {
	return xxx_messageInfo_NotifyCollationResponse.Size(m)
}
func (m *NotifyCollationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyCollationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyCollationResponse proto.InternalMessageInfo

func (m *NotifyCollationResponse) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *NotifyCollationResponse) GetIsValid() bool {
	if m != nil {
		return m.IsValid
	}
	return false
}

type GetCollationRequest struct {
	MetaMsg              *MetaMsg `protobuf:"bytes,1,opt,name=metaMsg,proto3" json:"metaMsg,omitempty"`
	ShardID              int64    `protobuf:"varint,2,opt,name=shardID,proto3" json:"shardID,omitempty"`
	Period               int64    `protobuf:"varint,3,opt,name=period,proto3" json:"period,omitempty"`
	Hash                 string   `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCollationRequest) Reset()         { *m = GetCollationRequest{} }
func (m *GetCollationRequest) String() string { return proto.CompactTextString(m) }
func (*GetCollationRequest) ProtoMessage()    {}
func (*GetCollationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{3}
}
func (m *GetCollationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCollationRequest.Unmarshal(m, b)
}
func (m *GetCollationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCollationRequest.Marshal(b, m, deterministic)
}
func (m *GetCollationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCollationRequest.Merge(m, src)
}
func (m *GetCollationRequest) XXX_Size() int {
	return xxx_messageInfo_GetCollationRequest.Size(m)
}
func (m *GetCollationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCollationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCollationRequest proto.InternalMessageInfo

func (m *GetCollationRequest) GetMetaMsg() *MetaMsg {
	if m != nil {
		return m.MetaMsg
	}
	return nil
}

func (m *GetCollationRequest) GetShardID() int64 {
	if m != nil {
		return m.ShardID
	}
	return 0
}

func (m *GetCollationRequest) GetPeriod() int64 {
	if m != nil {
		return m.Period
	}
	return 0
}

func (m *GetCollationRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type GetCollationResponse struct {
	Response             *Response          `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Collation            *message.Collation `protobuf:"bytes,3,opt,name=collation,proto3" json:"collation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetCollationResponse) Reset()         { *m = GetCollationResponse{} }
func (m *GetCollationResponse) String() string { return proto.CompactTextString(m) }
func (*GetCollationResponse) ProtoMessage()    {}
func (*GetCollationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{4}
}
func (m *GetCollationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCollationResponse.Unmarshal(m, b)
}
func (m *GetCollationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCollationResponse.Marshal(b, m, deterministic)
}
func (m *GetCollationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCollationResponse.Merge(m, src)
}
func (m *GetCollationResponse) XXX_Size() int {
	return xxx_messageInfo_GetCollationResponse.Size(m)
}
func (m *GetCollationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCollationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCollationResponse proto.InternalMessageInfo

func (m *GetCollationResponse) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *GetCollationResponse) GetCollation() *message.Collation {
	if m != nil {
		return m.Collation
	}
	return nil
}

type NotifyPubSubRequest struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyPubSubRequest) Reset()         { *m = NotifyPubSubRequest{} }
func (m *NotifyPubSubRequest) String() string { return proto.CompactTextString(m) }
func (*NotifyPubSubRequest) ProtoMessage()    {}
func (*NotifyPubSubRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{5}
}
func (m *NotifyPubSubRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyPubSubRequest.Unmarshal(m, b)
}
func (m *NotifyPubSubRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyPubSubRequest.Marshal(b, m, deterministic)
}
func (m *NotifyPubSubRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyPubSubRequest.Merge(m, src)
}
func (m *NotifyPubSubRequest) XXX_Size() int {
	return xxx_messageInfo_NotifyPubSubRequest.Size(m)
}
func (m *NotifyPubSubRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyPubSubRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyPubSubRequest proto.InternalMessageInfo

func (m *NotifyPubSubRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *NotifyPubSubRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type NotifyPubSubResponse struct {
	Response             *Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	IsValid              bool      `protobuf:"varint,2,opt,name=isValid,proto3" json:"isValid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *NotifyPubSubResponse) Reset()         { *m = NotifyPubSubResponse{} }
func (m *NotifyPubSubResponse) String() string { return proto.CompactTextString(m) }
func (*NotifyPubSubResponse) ProtoMessage()    {}
func (*NotifyPubSubResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{6}
}
func (m *NotifyPubSubResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyPubSubResponse.Unmarshal(m, b)
}
func (m *NotifyPubSubResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyPubSubResponse.Marshal(b, m, deterministic)
}
func (m *NotifyPubSubResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyPubSubResponse.Merge(m, src)
}
func (m *NotifyPubSubResponse) XXX_Size() int {
	return xxx_messageInfo_NotifyPubSubResponse.Size(m)
}
func (m *NotifyPubSubResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyPubSubResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyPubSubResponse proto.InternalMessageInfo

func (m *NotifyPubSubResponse) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *NotifyPubSubResponse) GetIsValid() bool {
	if m != nil {
		return m.IsValid
	}
	return false
}

type Response struct {
	Status               Response_Status `protobuf:"varint,1,opt,name=status,proto3,enum=proto.event.Response_Status" json:"status,omitempty"`
	Message              string          `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{7}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() Response_Status {
	if m != nil {
		return m.Status
	}
	return Response_SUCCESS
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*MetaMsg)(nil), "proto.event.MetaMsg")
	proto.RegisterType((*NotifyCollationRequest)(nil), "proto.event.NotifyCollationRequest")
	proto.RegisterType((*NotifyCollationResponse)(nil), "proto.event.NotifyCollationResponse")
	proto.RegisterType((*GetCollationRequest)(nil), "proto.event.GetCollationRequest")
	proto.RegisterType((*GetCollationResponse)(nil), "proto.event.GetCollationResponse")
	proto.RegisterType((*NotifyPubSubRequest)(nil), "proto.event.NotifyPubSubRequest")
	proto.RegisterType((*NotifyPubSubResponse)(nil), "proto.event.NotifyPubSubResponse")
	proto.RegisterType((*Response)(nil), "proto.event.Response")
	proto.RegisterEnum("proto.event.Response_Status", Response_Status_name, Response_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EventClient is the client API for Event service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventClient interface {
	NotifyCollation(ctx context.Context, in *NotifyCollationRequest, opts ...grpc.CallOption) (*NotifyCollationResponse, error)
	NotifyPubSub(ctx context.Context, in *NotifyPubSubRequest, opts ...grpc.CallOption) (*NotifyPubSubResponse, error)
	GetCollation(ctx context.Context, in *GetCollationRequest, opts ...grpc.CallOption) (*GetCollationResponse, error)
}

type eventClient struct {
	cc *grpc.ClientConn
}

func NewEventClient(cc *grpc.ClientConn) EventClient {
	return &eventClient{cc}
}

func (c *eventClient) NotifyCollation(ctx context.Context, in *NotifyCollationRequest, opts ...grpc.CallOption) (*NotifyCollationResponse, error) {
	out := new(NotifyCollationResponse)
	err := c.cc.Invoke(ctx, "/proto.event.Event/NotifyCollation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventClient) NotifyPubSub(ctx context.Context, in *NotifyPubSubRequest, opts ...grpc.CallOption) (*NotifyPubSubResponse, error) {
	out := new(NotifyPubSubResponse)
	err := c.cc.Invoke(ctx, "/proto.event.Event/NotifyPubSub", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventClient) GetCollation(ctx context.Context, in *GetCollationRequest, opts ...grpc.CallOption) (*GetCollationResponse, error) {
	out := new(GetCollationResponse)
	err := c.cc.Invoke(ctx, "/proto.event.Event/GetCollation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventServer is the server API for Event service.
type EventServer interface {
	NotifyCollation(context.Context, *NotifyCollationRequest) (*NotifyCollationResponse, error)
	NotifyPubSub(context.Context, *NotifyPubSubRequest) (*NotifyPubSubResponse, error)
	GetCollation(context.Context, *GetCollationRequest) (*GetCollationResponse, error)
}

func RegisterEventServer(s *grpc.Server, srv EventServer) {
	s.RegisterService(&_Event_serviceDesc, srv)
}

func _Event_NotifyCollation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyCollationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServer).NotifyCollation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.event.Event/NotifyCollation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServer).NotifyCollation(ctx, req.(*NotifyCollationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Event_NotifyPubSub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyPubSubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServer).NotifyPubSub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.event.Event/NotifyPubSub",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServer).NotifyPubSub(ctx, req.(*NotifyPubSubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Event_GetCollation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCollationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServer).GetCollation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.event.Event/GetCollation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServer).GetCollation(ctx, req.(*GetCollationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Event_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.event.Event",
	HandlerType: (*EventServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifyCollation",
			Handler:    _Event_NotifyCollation_Handler,
		},
		{
			MethodName: "NotifyPubSub",
			Handler:    _Event_NotifyPubSub_Handler,
		},
		{
			MethodName: "GetCollation",
			Handler:    _Event_GetCollation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "event.proto",
}

func init() { proto.RegisterFile("event.proto", fileDescriptor_2d17a9d3f0ddf27e) }

var fileDescriptor_2d17a9d3f0ddf27e = []byte{
	// 464 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0xc1, 0x6f, 0xd3, 0x30,
	0x14, 0xc6, 0x9b, 0x75, 0x6b, 0x9a, 0xd7, 0x09, 0x26, 0xaf, 0x8c, 0xa8, 0xe2, 0x50, 0x0c, 0x87,
	0x5d, 0x96, 0x8a, 0x82, 0xb8, 0x02, 0x2a, 0x05, 0x4d, 0x62, 0x08, 0x39, 0x2a, 0x47, 0x24, 0x27,
	0xf5, 0x12, 0x4b, 0x6d, 0x6c, 0x62, 0x07, 0x89, 0x0b, 0x82, 0x33, 0x67, 0xfe, 0x5f, 0x14, 0x27,
	0xde, 0x92, 0x12, 0x4d, 0x08, 0xb4, 0x53, 0xfc, 0xda, 0xcf, 0xbf, 0xf7, 0xbd, 0xcf, 0x36, 0x8c,
	0xd8, 0x17, 0x96, 0xe9, 0x40, 0xe6, 0x42, 0x0b, 0x34, 0x32, 0x9f, 0xc0, 0xfc, 0x34, 0x79, 0x99,
	0x70, 0x9d, 0x16, 0x51, 0x10, 0x8b, 0xed, 0x8c, 0xe9, 0x34, 0x67, 0x8a, 0xd1, 0x3c, 0x4e, 0x67,
	0x2a, 0xa5, 0xf9, 0x9a, 0x67, 0xc9, 0x99, 0x9c, 0xcb, 0x33, 0x29, 0xe2, 0x99, 0x8c, 0x66, 0x5b,
	0xa6, 0x14, 0x4d, 0x98, 0xfd, 0x56, 0x38, 0xec, 0x81, 0x7b, 0xc1, 0x34, 0xbd, 0x50, 0x09, 0xfe,
	0xee, 0xc0, 0xc9, 0x7b, 0xa1, 0xf9, 0xe5, 0xd7, 0x85, 0xd8, 0x6c, 0xa8, 0xe6, 0x22, 0x23, 0xec,
	0x73, 0xc1, 0x94, 0x46, 0x01, 0xb8, 0xdb, 0x4a, 0xe5, 0x3b, 0x53, 0xe7, 0x74, 0x34, 0x1f, 0x07,
	0x0d, 0x1b, 0x41, 0x4d, 0x20, 0x56, 0x84, 0x9e, 0x83, 0x17, 0x5b, 0x86, 0xbf, 0x67, 0x76, 0xf8,
	0xf5, 0x0e, 0xdb, 0xfe, 0xba, 0xc7, 0xb5, 0x14, 0x5f, 0xc2, 0xfd, 0x3f, 0x1c, 0x28, 0x29, 0x32,
	0xc5, 0xd0, 0x13, 0x18, 0xe6, 0xf5, 0xba, 0xf6, 0x70, 0xaf, 0xe5, 0xc1, 0x0a, 0xc9, 0x95, 0x0c,
	0xf9, 0xe0, 0x72, 0xf5, 0x91, 0x6e, 0xf8, 0xda, 0x78, 0x18, 0x12, 0x5b, 0xe2, 0x9f, 0x0e, 0x1c,
	0xbf, 0x65, 0xfa, 0xbf, 0xe7, 0xf4, 0xc1, 0x35, 0x51, 0x9f, 0xbf, 0x36, 0x1d, 0xfa, 0xc4, 0x96,
	0xe8, 0x04, 0x06, 0x92, 0xe5, 0x5c, 0xac, 0xfd, 0xbe, 0xf9, 0xa3, 0xae, 0x10, 0x82, 0xfd, 0x94,
	0xaa, 0xd4, 0xdf, 0x9f, 0x3a, 0xa7, 0x1e, 0x31, 0x6b, 0xfc, 0xc3, 0x81, 0x71, 0xdb, 0xcd, 0xbf,
	0xcf, 0xdc, 0x4a, 0xbe, 0xff, 0xf7, 0xc9, 0xbf, 0x80, 0xe3, 0x2a, 0xf9, 0x0f, 0x45, 0x14, 0x16,
	0x91, 0x0d, 0x64, 0x0c, 0x07, 0x5a, 0x48, 0x1e, 0x9b, 0xf6, 0x1e, 0xa9, 0x8a, 0x72, 0x88, 0x35,
	0xd5, 0xd4, 0xcc, 0x7c, 0x48, 0xcc, 0x1a, 0xc7, 0x30, 0x6e, 0x03, 0x6e, 0xe3, 0xdc, 0xbe, 0xc1,
	0xf0, 0x0a, 0xfc, 0x0c, 0x06, 0x4a, 0x53, 0x5d, 0x28, 0x83, 0xbd, 0x33, 0x7f, 0xd0, 0x89, 0x0d,
	0x42, 0xa3, 0x21, 0xb5, 0xb6, 0x64, 0xd7, 0x39, 0x18, 0xb6, 0x47, 0x6c, 0x89, 0x31, 0x0c, 0x2a,
	0x2d, 0x1a, 0x81, 0x1b, 0xae, 0x16, 0x8b, 0x65, 0x18, 0x1e, 0xf5, 0xca, 0xe2, 0xcd, 0xab, 0xf3,
	0x77, 0x2b, 0xb2, 0x3c, 0x72, 0xe6, 0xbf, 0xf6, 0xe0, 0x60, 0x59, 0xf2, 0xd1, 0x27, 0xb8, 0xbb,
	0x73, 0x53, 0xd1, 0xa3, 0x96, 0x81, 0xee, 0x97, 0x34, 0x79, 0x7c, 0xb3, 0xa8, 0x32, 0x8d, 0x7b,
	0x68, 0x05, 0x87, 0xcd, 0x38, 0xd1, 0xb4, 0x63, 0x5f, 0xeb, 0xa8, 0x26, 0x0f, 0x6f, 0x50, 0x34,
	0xb1, 0xcd, 0x9b, 0xb6, 0x83, 0xed, 0x78, 0x12, 0x3b, 0xd8, 0xae, 0x6b, 0x8a, 0x7b, 0xd1, 0xc0,
	0x68, 0x9e, 0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x15, 0x63, 0x04, 0xd4, 0xaa, 0x04, 0x00, 0x00,
}
