// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package proto_event

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import message "github.com/ethresearch/sharding-p2p-poc/pb/message"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Response_Status int32

const (
	Response_SUCCESS Response_Status = 0
	Response_FAILURE Response_Status = 1
)

var Response_Status_name = map[int32]string{
	0: "SUCCESS",
	1: "FAILURE",
}
var Response_Status_value = map[string]int32{
	"SUCCESS": 0,
	"FAILURE": 1,
}

func (x Response_Status) String() string {
	return proto.EnumName(Response_Status_name, int32(x))
}
func (Response_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_event_70ea54081db2824a, []int{3, 0}
}

type MetaMsg struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetaMsg) Reset()         { *m = MetaMsg{} }
func (m *MetaMsg) String() string { return proto.CompactTextString(m) }
func (*MetaMsg) ProtoMessage()    {}
func (*MetaMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_70ea54081db2824a, []int{0}
}
func (m *MetaMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaMsg.Unmarshal(m, b)
}
func (m *MetaMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaMsg.Marshal(b, m, deterministic)
}
func (dst *MetaMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaMsg.Merge(dst, src)
}
func (m *MetaMsg) XXX_Size() int {
	return xxx_messageInfo_MetaMsg.Size(m)
}
func (m *MetaMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaMsg.DiscardUnknown(m)
}

var xxx_messageInfo_MetaMsg proto.InternalMessageInfo

type NewCollationNotifier struct {
	MetaMsg              *MetaMsg           `protobuf:"bytes,1,opt,name=metaMsg,proto3" json:"metaMsg,omitempty"`
	Collation            *message.Collation `protobuf:"bytes,2,opt,name=collation,proto3" json:"collation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *NewCollationNotifier) Reset()         { *m = NewCollationNotifier{} }
func (m *NewCollationNotifier) String() string { return proto.CompactTextString(m) }
func (*NewCollationNotifier) ProtoMessage()    {}
func (*NewCollationNotifier) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_70ea54081db2824a, []int{1}
}
func (m *NewCollationNotifier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewCollationNotifier.Unmarshal(m, b)
}
func (m *NewCollationNotifier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewCollationNotifier.Marshal(b, m, deterministic)
}
func (dst *NewCollationNotifier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewCollationNotifier.Merge(dst, src)
}
func (m *NewCollationNotifier) XXX_Size() int {
	return xxx_messageInfo_NewCollationNotifier.Size(m)
}
func (m *NewCollationNotifier) XXX_DiscardUnknown() {
	xxx_messageInfo_NewCollationNotifier.DiscardUnknown(m)
}

var xxx_messageInfo_NewCollationNotifier proto.InternalMessageInfo

func (m *NewCollationNotifier) GetMetaMsg() *MetaMsg {
	if m != nil {
		return m.MetaMsg
	}
	return nil
}

func (m *NewCollationNotifier) GetCollation() *message.Collation {
	if m != nil {
		return m.Collation
	}
	return nil
}

type NewCollationResponse struct {
	Response             *Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	IsValid              bool      `protobuf:"varint,2,opt,name=isValid,proto3" json:"isValid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *NewCollationResponse) Reset()         { *m = NewCollationResponse{} }
func (m *NewCollationResponse) String() string { return proto.CompactTextString(m) }
func (*NewCollationResponse) ProtoMessage()    {}
func (*NewCollationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_70ea54081db2824a, []int{2}
}
func (m *NewCollationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewCollationResponse.Unmarshal(m, b)
}
func (m *NewCollationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewCollationResponse.Marshal(b, m, deterministic)
}
func (dst *NewCollationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewCollationResponse.Merge(dst, src)
}
func (m *NewCollationResponse) XXX_Size() int {
	return xxx_messageInfo_NewCollationResponse.Size(m)
}
func (m *NewCollationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewCollationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewCollationResponse proto.InternalMessageInfo

func (m *NewCollationResponse) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *NewCollationResponse) GetIsValid() bool {
	if m != nil {
		return m.IsValid
	}
	return false
}

type Response struct {
	Status               Response_Status `protobuf:"varint,1,opt,name=status,proto3,enum=proto.event.Response_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_event_70ea54081db2824a, []int{3}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() Response_Status {
	if m != nil {
		return m.Status
	}
	return Response_SUCCESS
}

func init() {
	proto.RegisterType((*MetaMsg)(nil), "proto.event.MetaMsg")
	proto.RegisterType((*NewCollationNotifier)(nil), "proto.event.NewCollationNotifier")
	proto.RegisterType((*NewCollationResponse)(nil), "proto.event.NewCollationResponse")
	proto.RegisterType((*Response)(nil), "proto.event.Response")
	proto.RegisterEnum("proto.event.Response_Status", Response_Status_name, Response_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EventClient is the client API for Event service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventClient interface {
	// Sends a greeting
	NewCollation(ctx context.Context, in *NewCollationNotifier, opts ...grpc.CallOption) (*NewCollationResponse, error)
}

type eventClient struct {
	cc *grpc.ClientConn
}

func NewEventClient(cc *grpc.ClientConn) EventClient {
	return &eventClient{cc}
}

func (c *eventClient) NewCollation(ctx context.Context, in *NewCollationNotifier, opts ...grpc.CallOption) (*NewCollationResponse, error) {
	out := new(NewCollationResponse)
	err := c.cc.Invoke(ctx, "/proto.event.Event/NewCollation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventServer is the server API for Event service.
type EventServer interface {
	// Sends a greeting
	NewCollation(context.Context, *NewCollationNotifier) (*NewCollationResponse, error)
}

func RegisterEventServer(s *grpc.Server, srv EventServer) {
	s.RegisterService(&_Event_serviceDesc, srv)
}

func _Event_NewCollation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewCollationNotifier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventServer).NewCollation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.event.Event/NewCollation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventServer).NewCollation(ctx, req.(*NewCollationNotifier))
	}
	return interceptor(ctx, in, info, handler)
}

var _Event_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.event.Event",
	HandlerType: (*EventServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewCollation",
			Handler:    _Event_NewCollation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "event.proto",
}

func init() { proto.RegisterFile("event.proto", fileDescriptor_event_70ea54081db2824a) }

var fileDescriptor_event_70ea54081db2824a = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x37, 0xc1, 0x75, 0x7b, 0x15, 0x19, 0x61, 0x42, 0x19, 0x1e, 0x34, 0x27, 0x2f, 0x4b,
	0xb1, 0x8a, 0x67, 0x65, 0x4c, 0x10, 0xdc, 0x0e, 0x29, 0xdb, 0x55, 0xb2, 0xee, 0xd9, 0x06, 0xb6,
	0xa6, 0x24, 0x99, 0xde, 0xfc, 0xdb, 0x65, 0x59, 0x33, 0x57, 0x98, 0xa7, 0xd7, 0xf7, 0xf8, 0x7c,
	0x7f, 0x34, 0x10, 0xe2, 0x17, 0x96, 0x96, 0x55, 0x5a, 0x59, 0x45, 0x42, 0x37, 0x98, 0x3b, 0x0d,
	0x9f, 0x73, 0x69, 0x8b, 0xed, 0x92, 0x65, 0x6a, 0x13, 0xa3, 0x2d, 0x34, 0x1a, 0x14, 0x3a, 0x2b,
	0x62, 0x53, 0x08, 0xbd, 0x92, 0x65, 0x3e, 0xaa, 0x92, 0x6a, 0x54, 0xa9, 0x2c, 0xae, 0x96, 0xf1,
	0x06, 0x8d, 0x11, 0x39, 0xfa, 0xb9, 0xb7, 0xa3, 0x3d, 0x08, 0xa6, 0x68, 0xc5, 0xd4, 0xe4, 0xf4,
	0x07, 0x06, 0x33, 0xfc, 0x1e, 0xab, 0xf5, 0x5a, 0x58, 0xa9, 0xca, 0x99, 0xb2, 0xf2, 0x53, 0xa2,
	0x26, 0x0c, 0x82, 0xcd, 0x1e, 0x89, 0xda, 0x37, 0xed, 0xbb, 0x30, 0x19, 0xb0, 0xa3, 0x0e, 0xac,
	0x96, 0x73, 0x0f, 0x91, 0x27, 0xe8, 0x65, 0xde, 0x24, 0x3a, 0x73, 0x8a, 0xa8, 0x56, 0xf8, 0xec,
	0x43, 0x08, 0xff, 0x43, 0x69, 0xd6, 0xcc, 0xe7, 0x68, 0x2a, 0x55, 0x1a, 0x24, 0xf7, 0xd0, 0xd5,
	0xf5, 0x77, 0x5d, 0xe0, 0xaa, 0x51, 0xc0, 0x83, 0xfc, 0x80, 0x91, 0x08, 0x02, 0x69, 0x16, 0x62,
	0x2d, 0x57, 0xae, 0x40, 0x97, 0xfb, 0x95, 0xae, 0xa0, 0x7b, 0x30, 0x7e, 0x84, 0x8e, 0xb1, 0xc2,
	0x6e, 0x8d, 0xb3, 0xbd, 0x4c, 0xae, 0x4f, 0xda, 0xb2, 0xd4, 0x31, 0xbc, 0x66, 0x29, 0x85, 0xce,
	0xfe, 0x42, 0x42, 0x08, 0xd2, 0xf9, 0x78, 0x3c, 0x49, 0xd3, 0x7e, 0x6b, 0xb7, 0xbc, 0xbe, 0xbc,
	0xbd, 0xcf, 0xf9, 0xa4, 0xdf, 0x4e, 0x3e, 0xe0, 0x7c, 0xb2, 0x33, 0x21, 0x0b, 0xb8, 0x38, 0xfe,
	0x27, 0x72, 0xdb, 0x88, 0x38, 0xf5, 0xdc, 0xc3, 0xff, 0x11, 0xdf, 0x88, 0xb6, 0x96, 0x1d, 0xc7,
	0x3c, 0xfc, 0x06, 0x00, 0x00, 0xff, 0xff, 0x9e, 0xb2, 0xbd, 0x80, 0x1b, 0x02, 0x00, 0x00,
}
