- name: Git clone sharding-p2p-poc
  git:
    repo: 'https://github.com/ethresearch/sharding-p2p-poc.git'
    dest: "/home/ubuntu/sharding-p2p-poc"
    version: master
    accept_hostkey: true
    update: true

- name: Build docker image
  become: true
  docker_image:
    path: "/home/ubuntu/sharding-p2p-poc"
    name: ethereum/sharding-p2p-poc:testing
    dockerfile: docker/dev.Dockerfile
    nocache: true
    force: true
    rm: true
    push: false