---
- name: Start docker containers
  become: true
  docker_container:
    name: peer_{{ item }}
    image: ethresearch/sharding-p2p-poc:testing
    pull: yes
    state: started
    restart_policy: always
    memory: 4g
    privileged: true
    published_ports:
      - "{{ item }}:10000" # listen port
      - "{{ 100 + item|int }}:13000" # RPC port
    command: [
      "sh -c \"./sharding-p2p-poc -verbose -ip=0.0.0.0 -seed={{ item }}\""
    ]
    env:
      JAEGER_AGENT_HOST: "{{hostvars[inventory_hostname]['groups']['log_collector'][0].split('@')[1]}}"
      JAEGER_AGENT_PORT: 6831
  with_sequence: end="{{ p2p_nodes_end }}" start="{{ p2p_nodes_start }}"