// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package protocols_p2p

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// AddPeer
type RPCAddPeerReq struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Seed                 int64    `protobuf:"varint,3,opt,name=seed,proto3" json:"seed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPCAddPeerReq) Reset()         { *m = RPCAddPeerReq{} }
func (m *RPCAddPeerReq) String() string { return proto.CompactTextString(m) }
func (*RPCAddPeerReq) ProtoMessage()    {}
func (*RPCAddPeerReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_8c7370dac0d2595f, []int{0}
}
func (m *RPCAddPeerReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPCAddPeerReq.Unmarshal(m, b)
}
func (m *RPCAddPeerReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPCAddPeerReq.Marshal(b, m, deterministic)
}
func (dst *RPCAddPeerReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCAddPeerReq.Merge(dst, src)
}
func (m *RPCAddPeerReq) XXX_Size() int {
	return xxx_messageInfo_RPCAddPeerReq.Size(m)
}
func (m *RPCAddPeerReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCAddPeerReq.DiscardUnknown(m)
}

var xxx_messageInfo_RPCAddPeerReq proto.InternalMessageInfo

func (m *RPCAddPeerReq) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *RPCAddPeerReq) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *RPCAddPeerReq) GetSeed() int64 {
	if m != nil {
		return m.Seed
	}
	return 0
}

// ListShardPeer
type RPCListShardPeerReq struct {
	ShardID              int64    `protobuf:"varint,1,opt,name=shardID,proto3" json:"shardID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPCListShardPeerReq) Reset()         { *m = RPCListShardPeerReq{} }
func (m *RPCListShardPeerReq) String() string { return proto.CompactTextString(m) }
func (*RPCListShardPeerReq) ProtoMessage()    {}
func (*RPCListShardPeerReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_8c7370dac0d2595f, []int{1}
}
func (m *RPCListShardPeerReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPCListShardPeerReq.Unmarshal(m, b)
}
func (m *RPCListShardPeerReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPCListShardPeerReq.Marshal(b, m, deterministic)
}
func (dst *RPCListShardPeerReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCListShardPeerReq.Merge(dst, src)
}
func (m *RPCListShardPeerReq) XXX_Size() int {
	return xxx_messageInfo_RPCListShardPeerReq.Size(m)
}
func (m *RPCListShardPeerReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCListShardPeerReq.DiscardUnknown(m)
}

var xxx_messageInfo_RPCListShardPeerReq proto.InternalMessageInfo

func (m *RPCListShardPeerReq) GetShardID() int64 {
	if m != nil {
		return m.ShardID
	}
	return 0
}

// SubscribeShard
type RPCSubscribeShardReq struct {
	ShardIDs             []int64  `protobuf:"varint,1,rep,packed,name=shardIDs,proto3" json:"shardIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPCSubscribeShardReq) Reset()         { *m = RPCSubscribeShardReq{} }
func (m *RPCSubscribeShardReq) String() string { return proto.CompactTextString(m) }
func (*RPCSubscribeShardReq) ProtoMessage()    {}
func (*RPCSubscribeShardReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_8c7370dac0d2595f, []int{2}
}
func (m *RPCSubscribeShardReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPCSubscribeShardReq.Unmarshal(m, b)
}
func (m *RPCSubscribeShardReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPCSubscribeShardReq.Marshal(b, m, deterministic)
}
func (dst *RPCSubscribeShardReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCSubscribeShardReq.Merge(dst, src)
}
func (m *RPCSubscribeShardReq) XXX_Size() int {
	return xxx_messageInfo_RPCSubscribeShardReq.Size(m)
}
func (m *RPCSubscribeShardReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCSubscribeShardReq.DiscardUnknown(m)
}

var xxx_messageInfo_RPCSubscribeShardReq proto.InternalMessageInfo

func (m *RPCSubscribeShardReq) GetShardIDs() []int64 {
	if m != nil {
		return m.ShardIDs
	}
	return nil
}

// UnsubscribeShard
type RPCUnsubscribeShardReq struct {
	ShardIDs             []int64  `protobuf:"varint,1,rep,packed,name=shardIDs,proto3" json:"shardIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPCUnsubscribeShardReq) Reset()         { *m = RPCUnsubscribeShardReq{} }
func (m *RPCUnsubscribeShardReq) String() string { return proto.CompactTextString(m) }
func (*RPCUnsubscribeShardReq) ProtoMessage()    {}
func (*RPCUnsubscribeShardReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_8c7370dac0d2595f, []int{3}
}
func (m *RPCUnsubscribeShardReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPCUnsubscribeShardReq.Unmarshal(m, b)
}
func (m *RPCUnsubscribeShardReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPCUnsubscribeShardReq.Marshal(b, m, deterministic)
}
func (dst *RPCUnsubscribeShardReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCUnsubscribeShardReq.Merge(dst, src)
}
func (m *RPCUnsubscribeShardReq) XXX_Size() int {
	return xxx_messageInfo_RPCUnsubscribeShardReq.Size(m)
}
func (m *RPCUnsubscribeShardReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCUnsubscribeShardReq.DiscardUnknown(m)
}

var xxx_messageInfo_RPCUnsubscribeShardReq proto.InternalMessageInfo

func (m *RPCUnsubscribeShardReq) GetShardIDs() []int64 {
	if m != nil {
		return m.ShardIDs
	}
	return nil
}

// GetSubscribedShard
type RPCGetSubscribedShardReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPCGetSubscribedShardReq) Reset()         { *m = RPCGetSubscribedShardReq{} }
func (m *RPCGetSubscribedShardReq) String() string { return proto.CompactTextString(m) }
func (*RPCGetSubscribedShardReq) ProtoMessage()    {}
func (*RPCGetSubscribedShardReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_8c7370dac0d2595f, []int{4}
}
func (m *RPCGetSubscribedShardReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPCGetSubscribedShardReq.Unmarshal(m, b)
}
func (m *RPCGetSubscribedShardReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPCGetSubscribedShardReq.Marshal(b, m, deterministic)
}
func (dst *RPCGetSubscribedShardReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCGetSubscribedShardReq.Merge(dst, src)
}
func (m *RPCGetSubscribedShardReq) XXX_Size() int {
	return xxx_messageInfo_RPCGetSubscribedShardReq.Size(m)
}
func (m *RPCGetSubscribedShardReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCGetSubscribedShardReq.DiscardUnknown(m)
}

var xxx_messageInfo_RPCGetSubscribedShardReq proto.InternalMessageInfo

type RPCGetSubscribedShardReply struct {
	ShardIDs             []int64  `protobuf:"varint,1,rep,packed,name=shardIDs,proto3" json:"shardIDs,omitempty"`
	Status               bool     `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPCGetSubscribedShardReply) Reset()         { *m = RPCGetSubscribedShardReply{} }
func (m *RPCGetSubscribedShardReply) String() string { return proto.CompactTextString(m) }
func (*RPCGetSubscribedShardReply) ProtoMessage()    {}
func (*RPCGetSubscribedShardReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_8c7370dac0d2595f, []int{5}
}
func (m *RPCGetSubscribedShardReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPCGetSubscribedShardReply.Unmarshal(m, b)
}
func (m *RPCGetSubscribedShardReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPCGetSubscribedShardReply.Marshal(b, m, deterministic)
}
func (dst *RPCGetSubscribedShardReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCGetSubscribedShardReply.Merge(dst, src)
}
func (m *RPCGetSubscribedShardReply) XXX_Size() int {
	return xxx_messageInfo_RPCGetSubscribedShardReply.Size(m)
}
func (m *RPCGetSubscribedShardReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCGetSubscribedShardReply.DiscardUnknown(m)
}

var xxx_messageInfo_RPCGetSubscribedShardReply proto.InternalMessageInfo

func (m *RPCGetSubscribedShardReply) GetShardIDs() []int64 {
	if m != nil {
		return m.ShardIDs
	}
	return nil
}

func (m *RPCGetSubscribedShardReply) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

// BroadcastCollation
type RPCBroadcastCollationReq struct {
	ShardID              int64    `protobuf:"varint,1,opt,name=shardID,proto3" json:"shardID,omitempty"`
	Number               int32    `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Size                 int32    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Period               int32    `protobuf:"varint,4,opt,name=period,proto3" json:"period,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPCBroadcastCollationReq) Reset()         { *m = RPCBroadcastCollationReq{} }
func (m *RPCBroadcastCollationReq) String() string { return proto.CompactTextString(m) }
func (*RPCBroadcastCollationReq) ProtoMessage()    {}
func (*RPCBroadcastCollationReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_8c7370dac0d2595f, []int{6}
}
func (m *RPCBroadcastCollationReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPCBroadcastCollationReq.Unmarshal(m, b)
}
func (m *RPCBroadcastCollationReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPCBroadcastCollationReq.Marshal(b, m, deterministic)
}
func (dst *RPCBroadcastCollationReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCBroadcastCollationReq.Merge(dst, src)
}
func (m *RPCBroadcastCollationReq) XXX_Size() int {
	return xxx_messageInfo_RPCBroadcastCollationReq.Size(m)
}
func (m *RPCBroadcastCollationReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCBroadcastCollationReq.DiscardUnknown(m)
}

var xxx_messageInfo_RPCBroadcastCollationReq proto.InternalMessageInfo

func (m *RPCBroadcastCollationReq) GetShardID() int64 {
	if m != nil {
		return m.ShardID
	}
	return 0
}

func (m *RPCBroadcastCollationReq) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *RPCBroadcastCollationReq) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *RPCBroadcastCollationReq) GetPeriod() int32 {
	if m != nil {
		return m.Period
	}
	return 0
}

type RPCReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Status               bool     `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPCReply) Reset()         { *m = RPCReply{} }
func (m *RPCReply) String() string { return proto.CompactTextString(m) }
func (*RPCReply) ProtoMessage()    {}
func (*RPCReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_8c7370dac0d2595f, []int{7}
}
func (m *RPCReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPCReply.Unmarshal(m, b)
}
func (m *RPCReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPCReply.Marshal(b, m, deterministic)
}
func (dst *RPCReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCReply.Merge(dst, src)
}
func (m *RPCReply) XXX_Size() int {
	return xxx_messageInfo_RPCReply.Size(m)
}
func (m *RPCReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCReply.DiscardUnknown(m)
}

var xxx_messageInfo_RPCReply proto.InternalMessageInfo

func (m *RPCReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RPCReply) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*RPCAddPeerReq)(nil), "protocols.p2p.RPCAddPeerReq")
	proto.RegisterType((*RPCListShardPeerReq)(nil), "protocols.p2p.RPCListShardPeerReq")
	proto.RegisterType((*RPCSubscribeShardReq)(nil), "protocols.p2p.RPCSubscribeShardReq")
	proto.RegisterType((*RPCUnsubscribeShardReq)(nil), "protocols.p2p.RPCUnsubscribeShardReq")
	proto.RegisterType((*RPCGetSubscribedShardReq)(nil), "protocols.p2p.RPCGetSubscribedShardReq")
	proto.RegisterType((*RPCGetSubscribedShardReply)(nil), "protocols.p2p.RPCGetSubscribedShardReply")
	proto.RegisterType((*RPCBroadcastCollationReq)(nil), "protocols.p2p.RPCBroadcastCollationReq")
	proto.RegisterType((*RPCReply)(nil), "protocols.p2p.RPCReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PocClient is the client API for Poc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PocClient interface {
	// Sends a greeting
	AddPeer(ctx context.Context, in *RPCAddPeerReq, opts ...grpc.CallOption) (*RPCReply, error)
	ListShardPeer(ctx context.Context, in *RPCListShardPeerReq, opts ...grpc.CallOption) (*RPCReply, error)
	SubscribeShard(ctx context.Context, in *RPCSubscribeShardReq, opts ...grpc.CallOption) (*RPCReply, error)
	UnsubscribeShard(ctx context.Context, in *RPCUnsubscribeShardReq, opts ...grpc.CallOption) (*RPCReply, error)
	GetSubscribedShard(ctx context.Context, in *RPCGetSubscribedShardReq, opts ...grpc.CallOption) (*RPCGetSubscribedShardReply, error)
	BroadcastCollation(ctx context.Context, in *RPCBroadcastCollationReq, opts ...grpc.CallOption) (*RPCReply, error)
}

type pocClient struct {
	cc *grpc.ClientConn
}

func NewPocClient(cc *grpc.ClientConn) PocClient {
	return &pocClient{cc}
}

func (c *pocClient) AddPeer(ctx context.Context, in *RPCAddPeerReq, opts ...grpc.CallOption) (*RPCReply, error) {
	out := new(RPCReply)
	err := c.cc.Invoke(ctx, "/protocols.p2p.Poc/AddPeer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pocClient) ListShardPeer(ctx context.Context, in *RPCListShardPeerReq, opts ...grpc.CallOption) (*RPCReply, error) {
	out := new(RPCReply)
	err := c.cc.Invoke(ctx, "/protocols.p2p.Poc/ListShardPeer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pocClient) SubscribeShard(ctx context.Context, in *RPCSubscribeShardReq, opts ...grpc.CallOption) (*RPCReply, error) {
	out := new(RPCReply)
	err := c.cc.Invoke(ctx, "/protocols.p2p.Poc/SubscribeShard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pocClient) UnsubscribeShard(ctx context.Context, in *RPCUnsubscribeShardReq, opts ...grpc.CallOption) (*RPCReply, error) {
	out := new(RPCReply)
	err := c.cc.Invoke(ctx, "/protocols.p2p.Poc/UnsubscribeShard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pocClient) GetSubscribedShard(ctx context.Context, in *RPCGetSubscribedShardReq, opts ...grpc.CallOption) (*RPCGetSubscribedShardReply, error) {
	out := new(RPCGetSubscribedShardReply)
	err := c.cc.Invoke(ctx, "/protocols.p2p.Poc/GetSubscribedShard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pocClient) BroadcastCollation(ctx context.Context, in *RPCBroadcastCollationReq, opts ...grpc.CallOption) (*RPCReply, error) {
	out := new(RPCReply)
	err := c.cc.Invoke(ctx, "/protocols.p2p.Poc/BroadcastCollation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PocServer is the server API for Poc service.
type PocServer interface {
	// Sends a greeting
	AddPeer(context.Context, *RPCAddPeerReq) (*RPCReply, error)
	ListShardPeer(context.Context, *RPCListShardPeerReq) (*RPCReply, error)
	SubscribeShard(context.Context, *RPCSubscribeShardReq) (*RPCReply, error)
	UnsubscribeShard(context.Context, *RPCUnsubscribeShardReq) (*RPCReply, error)
	GetSubscribedShard(context.Context, *RPCGetSubscribedShardReq) (*RPCGetSubscribedShardReply, error)
	BroadcastCollation(context.Context, *RPCBroadcastCollationReq) (*RPCReply, error)
}

func RegisterPocServer(s *grpc.Server, srv PocServer) {
	s.RegisterService(&_Poc_serviceDesc, srv)
}

func _Poc_AddPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCAddPeerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PocServer).AddPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocols.p2p.Poc/AddPeer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PocServer).AddPeer(ctx, req.(*RPCAddPeerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Poc_ListShardPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCListShardPeerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PocServer).ListShardPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocols.p2p.Poc/ListShardPeer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PocServer).ListShardPeer(ctx, req.(*RPCListShardPeerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Poc_SubscribeShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCSubscribeShardReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PocServer).SubscribeShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocols.p2p.Poc/SubscribeShard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PocServer).SubscribeShard(ctx, req.(*RPCSubscribeShardReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Poc_UnsubscribeShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCUnsubscribeShardReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PocServer).UnsubscribeShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocols.p2p.Poc/UnsubscribeShard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PocServer).UnsubscribeShard(ctx, req.(*RPCUnsubscribeShardReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Poc_GetSubscribedShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCGetSubscribedShardReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PocServer).GetSubscribedShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocols.p2p.Poc/GetSubscribedShard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PocServer).GetSubscribedShard(ctx, req.(*RPCGetSubscribedShardReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Poc_BroadcastCollation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCBroadcastCollationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PocServer).BroadcastCollation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocols.p2p.Poc/BroadcastCollation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PocServer).BroadcastCollation(ctx, req.(*RPCBroadcastCollationReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Poc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocols.p2p.Poc",
	HandlerType: (*PocServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPeer",
			Handler:    _Poc_AddPeer_Handler,
		},
		{
			MethodName: "ListShardPeer",
			Handler:    _Poc_ListShardPeer_Handler,
		},
		{
			MethodName: "SubscribeShard",
			Handler:    _Poc_SubscribeShard_Handler,
		},
		{
			MethodName: "UnsubscribeShard",
			Handler:    _Poc_UnsubscribeShard_Handler,
		},
		{
			MethodName: "GetSubscribedShard",
			Handler:    _Poc_GetSubscribedShard_Handler,
		},
		{
			MethodName: "BroadcastCollation",
			Handler:    _Poc_BroadcastCollation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_rpc_8c7370dac0d2595f) }

var fileDescriptor_rpc_8c7370dac0d2595f = []byte{
	// 403 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x5f, 0xcb, 0xd3, 0x30,
	0x14, 0xc6, 0xed, 0xba, 0xbf, 0x07, 0x36, 0x24, 0xca, 0x0c, 0xc5, 0x8b, 0x12, 0x11, 0xeb, 0x4d,
	0x85, 0xe9, 0xa5, 0x37, 0xae, 0xc2, 0x10, 0x44, 0x42, 0xa6, 0xe0, 0x6d, 0xff, 0x04, 0xad, 0x74,
	0x4b, 0x4c, 0x32, 0x50, 0xbf, 0x80, 0x5f, 0xfb, 0xa5, 0x69, 0x37, 0xe8, 0xd2, 0x95, 0xf7, 0xbd,
	0x6a, 0x9e, 0x9e, 0xe7, 0x3c, 0x27, 0x3d, 0xfd, 0xc1, 0x42, 0xc9, 0x3c, 0x96, 0x4a, 0x18, 0x81,
	0x96, 0xf6, 0x91, 0x8b, 0x4a, 0xc7, 0x72, 0x23, 0xc9, 0x0e, 0x96, 0x8c, 0x26, 0x1f, 0x8a, 0x82,
	0x72, 0xae, 0x18, 0xff, 0x8d, 0x56, 0x30, 0x2a, 0x25, 0xf6, 0x42, 0x2f, 0x5a, 0xb0, 0x51, 0x29,
	0x11, 0x82, 0xb1, 0x14, 0xca, 0xe0, 0x51, 0xe8, 0x45, 0x13, 0x66, 0xcf, 0xf5, 0x3b, 0xcd, 0x79,
	0x81, 0xfd, 0xd0, 0x8b, 0x7c, 0x66, 0xcf, 0xe4, 0x0d, 0x3c, 0x61, 0x34, 0xf9, 0x5c, 0x6a, 0xb3,
	0xff, 0x99, 0xaa, 0x4b, 0x1c, 0x86, 0x99, 0xae, 0xf5, 0xa7, 0x8f, 0x36, 0xd3, 0x67, 0x67, 0x49,
	0x36, 0xf0, 0x94, 0xd1, 0x64, 0x7f, 0xca, 0x74, 0xae, 0xca, 0x8c, 0xdb, 0xae, 0xba, 0x23, 0x80,
	0x79, 0x6b, 0xd1, 0xd8, 0x0b, 0xfd, 0xc8, 0x67, 0x17, 0x4d, 0xde, 0xc1, 0x9a, 0xd1, 0xe4, 0xdb,
	0x51, 0x3f, 0xa8, 0x2b, 0x00, 0xcc, 0x68, 0xb2, 0xe3, 0xe6, 0x32, 0xac, 0x38, 0xf7, 0x11, 0x0a,
	0xc1, 0x8d, 0x9a, 0xac, 0xfe, 0x0e, 0xa5, 0xa2, 0x35, 0x4c, 0xb5, 0x49, 0xcd, 0x49, 0xdb, 0xd5,
	0xcc, 0x59, 0xab, 0xc8, 0x1f, 0x3b, 0x6d, 0xab, 0x44, 0x5a, 0xe4, 0xa9, 0x36, 0x89, 0xa8, 0xaa,
	0xd4, 0x94, 0xe2, 0x38, 0xb8, 0x8d, 0x3a, 0xed, 0x78, 0x3a, 0x64, 0x5c, 0xb5, 0x8b, 0x6e, 0x95,
	0x5d, 0x75, 0xf9, 0x8f, 0xdb, 0x55, 0x4f, 0x98, 0x3d, 0xd7, 0x5e, 0xc9, 0x55, 0x29, 0x0a, 0x3c,
	0x6e, 0xbc, 0x8d, 0x22, 0xef, 0x61, 0xce, 0x68, 0xd2, 0xdc, 0x1c, 0xc3, 0xec, 0xc0, 0xb5, 0x4e,
	0x7f, 0xf0, 0xf6, 0x5f, 0x9e, 0xe5, 0xad, 0x7b, 0x6f, 0xfe, 0x8f, 0xc1, 0xa7, 0x22, 0x47, 0x5b,
	0x98, 0xb5, 0x38, 0xa0, 0xe7, 0x71, 0x07, 0x96, 0xb8, 0x43, 0x4a, 0xf0, 0xcc, 0xad, 0xda, 0xd9,
	0xe4, 0x11, 0xfa, 0x02, 0xcb, 0x0e, 0x09, 0x88, 0xb8, 0xde, 0x6b, 0x54, 0x86, 0xf2, 0x28, 0xac,
	0xba, 0xa0, 0xa0, 0x17, 0xae, 0xd9, 0x41, 0x69, 0x28, 0xf1, 0x2b, 0x3c, 0xbe, 0xc6, 0x08, 0xbd,
	0x74, 0xed, 0x3d, 0xa8, 0x0d, 0xa5, 0xfe, 0x02, 0xe4, 0xa2, 0x84, 0x5e, 0xb9, 0x0d, 0xbd, 0x30,
	0x06, 0xaf, 0xef, 0x67, 0x6c, 0x66, 0x7d, 0x07, 0xe4, 0x42, 0xd6, 0x37, 0xab, 0x17, 0xc5, 0x81,
	0xaf, 0xc8, 0xa6, 0xb6, 0xf2, 0xf6, 0x2e, 0x00, 0x00, 0xff, 0xff, 0xc5, 0x36, 0xb7, 0xb4, 0x36,
	0x04, 0x00, 0x00,
}
